create extension if not exists pgcrypto;
create table if not exists public.users(id uuid primary key references auth.users(id) on delete cascade,email text,username text not null default 'Player',xp int not null default 0,level int not null default 1,coins int not null default 100,gems int not null default 0,streak int not null default 0,created_at timestamptz not null default now());
create table if not exists public.matches(id uuid primary key default gen_random_uuid(),room_code text unique check(room_code is null or room_code ~ '^[0-9]{6}$'),players jsonb not null default '[]',status text not null default 'waiting' check(status in('waiting','playing','finished','cancelled')),winner_id uuid references public.users(id),created_at timestamptz not null default now());
create table if not exists public.match_moves(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,player_id uuid not null references public.users(id),dice int not null check(dice between 1 and 6),token_id int not null check(token_id between 0 and 3),from_pos int not null,to_pos int not null, "timestamp" timestamptz not null default now());
create table if not exists public.missions(user_id uuid not null references public.users(id) on delete cascade,type text not null check(type in('daily_login','play_3','win_1')),progress int not null default 0,claimed bool not null default false,date date not null default (timezone('Asia/Kolkata',now()))::date,primary key(user_id,type,date));
create table if not exists public.ledger(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,type text not null check(type in('coins','gems')),amount int not null,reason text not null,created_at timestamptz not null default now());
alter table public.users enable row level security;alter table public.matches enable row level security;alter table public.match_moves enable row level security;alter table public.missions enable row level security;alter table public.ledger enable row level security;
create policy "Users are viewable by everyone" on public.users for select using(true);
create policy "Users update their profile" on public.users for update using(auth.uid()=id) with check(auth.uid()=id);
create policy "Matches readable by authenticated users" on public.matches for select to authenticated using(true);
create policy "Moves readable by authenticated users" on public.match_moves for select to authenticated using(true);
create policy "Own missions readable" on public.missions for select to authenticated using(auth.uid()=user_id);
create policy "Own ledger readable" on public.ledger for select to authenticated using(auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.users(id,email,username) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create index if not exists matches_status_created on public.matches(status,created_at desc);create index if not exists moves_match on public.match_moves(match_id,"timestamp");create index if not exists leaderboard_weekly on public.users(xp desc);
-- All authoritative writes (dice, moves, rewards, missions) use the Worker service role; never expose that key in VITE_* variables.
