import {Hono} from 'hono';import {cors} from 'hono/cors';import {applyMove,createGame,legalTokens,type GameState} from '../src/game/rules';
type Env={SUPABASE_URL:string;SUPABASE_SERVICE_ROLE_KEY:string};type Vars={uid:string};const app=new Hono<{Bindings:Env;Variables:Vars}>();app.use('*',cors({origin:'*',allowHeaders:['Content-Type','Authorization'],allowMethods:['GET','POST','OPTIONS']}));
async function db(env:Env,path:string,init:RequestInit={}){return fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...(init.headers||{})}})}
app.use('/api/*',async(c,next)=>{const token=c.req.header('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return c.json({error:'Sign in required'},401);const r=await fetch(`${c.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:c.env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return c.json({error:'Invalid session'},401);const u=await r.json() as {id:string};c.set('uid',u.id);await next()});
app.get('/health',c=>c.json({ok:true,service:'ludo-worker'}));
app.post('/api/matches',async c=>{const uid=c.get('uid'),body=await c.req.json().catch(()=>({}));const userRes=await db(c.env,`users?select=id,username&id=eq.${uid}`);const user=(await userRes.json() as any[])[0];if(!user)return c.json({error:'Profile missing; run supabase.sql and sign in again'},404);if(body.quick){const q=await db(c.env,'matches?select=*&status=eq.waiting&room_code=is.null&order=created_at.asc&limit=20');for(const m of await q.json() as any[]){if(m.players.length>=4||m.players.some((p:any)=>p.id===uid))continue;const players=[...m.players,{id:uid,username:user.username,color:['coral','teal','gold','violet'][m.players.length]}],state=createGame(players);await savePlayers(c.env,m.id,state,{status:'playing'});const updated={...m,players:state,status:'playing'};await broadcast(c.env,m.id,{type:'joined',match:updated});await updateMission(c.env,uid,'daily_login',1);return c.json({match:updated})}}const id=crypto.randomUUID(),code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0');const row={id,room_code:body.private?code:null,players:[{id:uid,username:user.username,color:'coral'}],status:'waiting'};const r=await db(c.env,'matches',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify(row)});if(!r.ok)return c.json({error:await r.text()},500);await updateMission(c.env,uid,'daily_login',1);return c.json({match:row,roomCode:body.private?code:null})});
app.post('/api/matches/join',async c=>{const uid=c.get('uid'),{code}=await c.req.json();if(!/^\d{6}$/.test(code))return c.json({error:'Enter a 6-digit room code'},400);const r=await db(c.env,`matches?select=*&room_code=eq.${code}&status=eq.waiting`);const rows=await r.json() as any[];const m=rows[0];if(!m)return c.json({error:'Room not found'},404);if(m.players.some((p:any)=>p.id===uid))return c.json({match:m});if(m.players.length>=4)return c.json({error:'Room is full'},409);const pr=await db(c.env,`users?select=id,username&id=eq.${uid}`),u=(await pr.json() as any[])[0];const colors=['coral','teal','gold','violet'];const players=[...m.players,{id:uid,username:u?.username||'Player',color:colors[m.players.length]}];const state=players.length>=2?createGame(players):null;const upd=await db(c.env,`matches?id=eq.${m.id}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify({players:state||players,status:state?'playing':'waiting',room_code:players.length>=4?null:m.room_code})});const updated=(await upd.json() as any[])[0];await broadcast(c.env,m.id,{type:'joined',match:updated});return c.json({match:updated})});
app.post('/api/matches/:id/roll',async c=>{const uid=c.get('uid'),id=c.req.param('id'),m=await getMatch(c.env,id);if(!m)return c.json({error:'Match not found'},404);const s=m.players as GameState;if(s.status!=='playing'||s.players[s.turn]?.id!==uid||s.dice!==null)return c.json({error:'Wait for your turn'},409);const dice=crypto.getRandomValues(new Uint32Array(1))[0]%6+1,sixes=dice===6?s.sixes+1:0;if(sixes>=3){const next={...s,turn:(s.turn+1)%s.players.length,dice:null,sixes:0};await savePlayers(c.env,id,next);await broadcast(c.env,id,{type:'turn_cancelled',playerId:uid,state:next});return c.json({dice,state:next,cancelled:true})}const next={...s,dice,sixes};await savePlayers(c.env,id,next);await broadcast(c.env,id,{type:'roll',playerId:uid,dice,state:next});return c.json({dice,state:next})});
app.post('/api/matches/:id/move',async c=>{const uid=c.get('uid'),id=c.req.param('id'),m=await getMatch(c.env,id);if(!m)return c.json({error:'Match not found'},404);try{const x=await c.req.json(),s=m.players as GameState,next=applyMove(s,uid,Number(x.tokenId),Number(x.from),Number(x.to),Number(x.dice));const patch:any={players:next,status:next.status,winner_id:next.winnerId};await savePlayers(c.env,id,next,patch);await db(c.env,'match_moves',{method:'POST',body:JSON.stringify({match_id:id,player_id:uid,dice:x.dice,token_id:x.tokenId,from_pos:x.from,to_pos:x.to})});await updateMission(c.env,uid,'play_3',1);if(next.status==='finished'){await award(c.env,uid,70,`match_win:${id}`);await updateMission(c.env,uid,'win_1',1)}await broadcast(c.env,id,{type:'move',playerId:uid,state:next});return c.json({state:next})}catch(e){return c.json({error:(e as Error).message},400)}});
app.post('/api/matches/:id/finish-reward',async c=>{const uid=c.get('uid'),m=await getMatch(c.env,c.req.param('id'));if(!m)return c.json({error:'Match not found'},404);const s=m.players as GameState;if(s.status!=='finished')return c.json({error:'Match is not finished'},409);const result=await db(c.env,`match_moves?select=id&match_id=eq.${m.id}&player_id=eq.${uid}`),moves=await result.json() as any[];if(!moves.length)return c.json({error:'No moves recorded'},403);await award(c.env,uid,20,`match_complete:${m.id}`);return c.json({ok:true})});
app.post('/api/missions/claim',async c=>{const uid=c.get('uid'),{type}=await c.req.json();if(!['daily_login','play_3','win_1'].includes(type))return c.json({error:'Unknown mission'},400);const date=istDate(),r=await db(c.env,`missions?select=*&user_id=eq.${uid}&type=eq.${type}&date=eq.${date}`),rows=await r.json() as any[],m=rows[0];const goal=type==='play_3'?3:1;if(!m||m.progress<goal||m.claimed)return c.json({error:'Mission is incomplete or already claimed'},409);await db(c.env,`missions?user_id=eq.${uid}&type=eq.${type}&date=eq.${date}`,{method:'PATCH',body:JSON.stringify({claimed:true})});await award(c.env,uid,50,`mission_${type}`);return c.json({ok:true,coins:50})});
app.post('/api/store/buy',async c=>{const uid=c.get('uid'),{itemId,price}=await c.req.json();const prices:Record<string,number>={sunset_dice:150,forest_board:250,royal_board:400};if(prices[itemId]!==price)return c.json({error:'Invalid item'},400);const r=await db(c.env,`users?select=coins&id=eq.${uid}`),user=(await r.json() as any[])[0];if(!user||user.coins<price)return c.json({error:'Not enough coins'},409);await db(c.env,`users?id=eq.${uid}`,{method:'PATCH',body:JSON.stringify({coins:user.coins-price})});await db(c.env,'ledger',{method:'POST',body:JSON.stringify({user_id:uid,type:'coins',amount:-price,reason:`shop_${itemId}`})});return c.json({ok:true,coins:user.coins-price})});
async function getMatch(env:Env,id:string){const r=await db(env,`matches?select=*&id=eq.${id}`);return((await r.json()) as any[])[0]}
async function savePlayers(env:Env,id:string,players:GameState,extra:any={}){return db(env,`matches?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({...extra,players})})}
async function award(env:Env,uid:string,coins:number,reason:string){const previous=await db(env,`ledger?select=id&user_id=eq.${uid}&reason=eq.${encodeURIComponent(reason)}&limit=1`);if(((await previous.json()) as any[]).length)return;const r=await db(env,`users?select=coins,xp&id=eq.${uid}`),u=(await r.json() as any[])[0];if(!u)return;const xp=reason.startsWith('match_complete:')?20:reason.startsWith('match_win:')?50:0;await db(env,`users?id=eq.${uid}`,{method:'PATCH',body:JSON.stringify({coins:u.coins+coins,xp:u.xp+xp,level:Math.floor((u.xp+xp)/100)})});await db(env,'ledger',{method:'POST',body:JSON.stringify({user_id:uid,type:'coins',amount:coins,reason})});}
function istDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
async function updateMission(env:Env,uid:string,type:string,delta:number){const date=istDate(),r=await db(env,`missions?select=*&user_id=eq.${uid}&type=eq.${type}&date=eq.${date}`),rows=await r.json() as any[];if(rows[0])await db(env,`missions?user_id=eq.${uid}&type=eq.${type}&date=eq.${date}`,{method:'PATCH',body:JSON.stringify({progress:Math.min(type==='play_3'?3:1,rows[0].progress+delta)})});else await db(env,'missions',{method:'POST',body:JSON.stringify({user_id:uid,type,progress:delta,claimed:false,date})})}
async function broadcast(env:Env,id:string,payload:any){await fetch(`${env.SUPABASE_URL}/realtime/v1/api/broadcast`,{method:'POST',headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json'},body:JSON.stringify({messages:[{topic:`match:${id}`,event:'game',payload}]})})}
export default app;
